services:

    hbbs:
        image: rustdesk/rustdesk-server:latest
        container_name: hbbs
        ports:
            - 21115:21115
            - 21116:21116
            - 21116:21116/udp
            - 21118:21118
        volumes:
            - ./hbbs:/root
        tty: true
        network_mode: host
        depends_on:
            - hbbr        
        command: hbbs
        restart: unless-stopped


    hbbr:
        image: rustdesk/rustdesk-server:latest
        container_name: hbbr
        ports:
            - "21117:21117"
            - "21119:21119"
        volumes:
            - ./hbbr:/root
        tty: true
        network_mode: host
        command: hbbr
        restart: unless-stopped        







    